apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonacci-api
  template:
    metadata:
      labels:
        app: fibonacci-api
    spec:
      containers:
      - name: fibonacci-api
        image: lisaelsa/fibonacciapi:latest
        ports:
        - containerPort: 5000
